# Week 2: Introduction to Pandas
As you have seen from the video, `pandas` is a popular Python library that is commonly used for data retrieval and manipulation tasks. This drill will help you get acclimated to the power of Pandas

In `exercise.py`, you will find a set of tasks to complete in order to ramp up your foundations. There is also a file called `tester.py` that you can run in order to see if your implementation works (through unit tests). Couple pieces of advice:

1. Take your time with this exercise. You want to make sure that you clearly understand the problem that is presented

2. Don't just copy solutions off of the Internet blindly. You can use resources such as Stack Overflow as helpers, but don't substitute the actual learning just for "completing the exercise". Your goal is to sharpen your problem solving

3. Collaborate at the "whiteboard-level" (like discuss approaches at high level/bounce ideas, but not exactly specific implementation details)

4. Work with other students in the Udemy Course (we have a Slack channel after all that you joined). Please refrain from sharing your solutions to the group. We would hate if the meat and potatoes of the problems got "spoiled". 

Good luck in this exercise!

Below are some cells you can run to double check your implementation

In [3]:
import exercise
import pandas as pd
import seaborn as sns

df = pd.read_csv('titanic_train.csv')

In [ ]:
#see what the dataframe looks like for purposes of this exercise
exercise.get_dataframe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Exercise 1

In [5]:
exercise.get_age_class_sex()

## Exercise 2

In [ ]:
exercise.get_age_class_sex_over_30()

## Exercise 3

In [ ]:
exercise.get_100th_person_info()

## Exercise 4

In [ ]:
exercise.calc_num_unique_ages()

## Exercise 5

In [ ]:
exercise.get_cabin_nulls_and_shape()

## Exercise 6

In [ ]:
exercise.drop_cabin_col()

## Exercise 7

In [ ]:
exercise.survived_within_class()

To test that your code works, you can go to the right sidebar and under `Terminals`, you'll see an entry called `Sandbox Terminal`. Open that terminal and run `python tester.py`

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3d0133b3-1875-4d7e-bf20-33b408f85deb' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>